apiVersion: v1
kind: Pod
metadata:
 name: job1
spec:
 containers:
 - args:
   - variational_autoencoder.py
   - /root/job1.csv
   - job1
   commandL
   - python
   image: wzheng33/vae:latest
   name: lenet-test-epoch
   volumeMounts:
   - mountPath: /root/
     name: task-pv-storage
 restartPolicy: Never
 volumes:
 - name:task-pv-storage
   persistentVolumeClaim:
     claimName: pv1-nfs