kind: Pod
apiVersion: v1
metadata:
  name: Needtoplaced
spec:
  restartPolicy: Never
  schedulerName: scheduler-need-to-be-replaced
  volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
      claimName: pvc1-nfs
  containers:
    - name: d-rnn
      image: zsl3203/drnn_log
      command: ["python"]
      args: ["d_rnn_log.py","10000","/root/drnn/Needtoplaced.csv","Needtoplaced"]
      volumeMounts:
      - mountPath: "/root/drnn"
        name: task-pv-storage
